# Generated by Django 5.2.17 on 2026-09-11 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
        ('theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSupervisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY_SUPERVISOR', 'مشرف رئيسي'), ('CO_SUPERVISOR', 'مشرف مشارك'), ('EXTERNAL_SUPERVISOR', 'مشرف خارجي'), ('ASSISTANT_SUPERVISOR', 'مشرف مساعد')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'بانتظار الاعتماد'), ('ACTIVE', 'نشط'), ('ENDED', 'منتهي'), ('REPLACED', 'تم الاستبدال')], default='PENDING_APPROVAL', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_supervision_assignments', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_assignments', to='supervision.supervisorprofile')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_assignments', to='theses.thesis')),
            ],
        ),
    ]
