# Generated by Django 5.2.17 on 2026-09-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_thesissupervisorassignment'),
        ('theses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'تحت المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='DRAFT', max_length=50)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='supervision.thesissupervisorassignment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_change_requests_created', to=settings.AUTH_USER_MODEL)),
                ('requested_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_supervisor_changes', to='supervision.supervisorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_change_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_change_requests', to='theses.thesis')),
            ],
        ),
    ]
