# Generated by Django 5.2.17 on 2026-09-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.TextField()),
                ('status', models.CharField(default='REGISTERED', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
        ),
    ]
