# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0002_academicenrollment_academicenrollmentevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_CREATED", "إنشاء قيد أكاديمي"),
                            ("ENROLLMENT_UPDATED", "تحديث القيد الأكاديمي"),
                            ("THESIS_REGISTERED", "تسجيل الرسالة العلمية"),
                            ("THESIS_STATUS_CHANGED", "تغيير حالة الرسالة"),
                            ("DOCUMENT_UPLOADED", "رفع مستند"),
                            ("DEFENSE_CREATED", "إنشاء لجنة مناقشة"),
                            ("DEFENSE_COMPLETED", "إتمام المناقشة"),
                            ("OTHER", "حدث آخر"),
                        ],
                        max_length=100,
                    ),
                ),
                ("title_ar", models.CharField(max_length=255)),
                ("description_ar", models.TextField(blank=True)),
                ("reference_type", models.CharField(blank=True, max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_history_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_history_events",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
