# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROGRAM_DIRECTOR", "مدير البرنامج"),
                    ("POSTGRADUATE_DIRECTOR", "مدير الدراسات العليا"),
                    ("DEAN", "عميد الكلية"),
                    ("VICE_DEAN", "وكيل الكلية"),
                    ("VICE_DEAN_POSTGRADUATE", "وكيل الدراسات العليا والبحوث"),
                    ("VP_POSTGRADUATE_RESEARCH", "نائب رئيس الجامعة لشئون الدراسات العليا والبحوث"),
                    ("STAFF", "موظف"),
                    ("REVIEWER", "مراجع"),
                    ("SUPERVISOR", "مشرف"),
                    ("STUDENT", "طالب"),
                ],
                default="STAFF",
                max_length=32,
            ),
        ),
    ]
