# Generated by Django 5.2.17 on 2026-09-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department')),
            ],
        ),
    ]
