# Generated by Django 5.2.17 on 2026-09-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=50)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='theses.thesis')),
            ],
        ),
    ]
